repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: ^(\.vscode/launch\.json|\.devcontainer/devcontainer\.json)$
      - id: pretty-format-json
        exclude: ^(\.vscode/launch\.json|\.devcontainer/devcontainer\.json)$
        args: [--autofix]
      - id: check-toml
      - id: check-yaml

exclude: \S*generated/
