services:

  devcontainer:
    build:
      context: .
      dockerfile: dev.Dockerfile

    volumes:
      - "./dynamic.yml:/dynamic.yml:rw"
      - ".:/workspace:cached"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - POSTGRES_HOST=db

    env_file:
      - .env

    cap_add:
      - CAP_SYS_ADMIN

      

    privileged: true
    command: [ "sleep", "infinity" ]

networks:
  default:
    external: true
    name: thesis_default
    