services:
  reverse-proxy:
    image: traefik:v3.4
    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic/conf/dynamic.yml
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 80
        protocol: tcp
        
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.role==manager

  sablier:
    image: sablierapp/sablier:1.9.0
    command:
      - start
      - --provider.name=docker_swarm
  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - reverse-proxy
    deploy:
      placement:
        constraints:
          - node.role==manager


  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role==manager

  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/thesis.agent

    volumes:
      - /:/host

    cap_add:
      - CAP_SYS_ADMIN
    ports:
      - target: 50051
        published: 50051
        protocol: tcp
        mode: host


    deploy:
      endpoint_mode: dnsrr
      mode: global
      placement:
        constraints:
          - node.role==worker

volumes:
  pgdata:

networks:
  default:
    external: true
    name: thesis_default
    