services:
  reverse-proxy:
    image: traefik:v3.4
    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic/conf/dynamic.yml
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - "8080:8080"
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.role==manager

  sablier:
    image: sablierapp/sablier:1.9.0
    command:
      - start
      - --provider.name=docker

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - reverse-proxy

    deploy:
      placement:
        constraints:
          - node.role==manager

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/thesis.agent

    volumes:
      - /fs:/fs:rw
      - /var/run/docker.sock:/var/run/docker.sock

    cap_add:
      - CAP_SYS_ADMIN

    deploy:
      mode: global
      placement:
        constraints:
          - node.role==worker

volumes:
  pgdata:
