services:
  devcontainer:
    build:
      context: .
      dockerfile: dev.Dockerfile

    volumes:
      - /home/bevzd/test/filesystem:/fs:rw
      - /home/bevzd/test/quotafs.img:/quotafs.img
      - ".:/workspace:cached"
      - etc_volume:/etc
      - pgdata:/pgdata
      # - /sys:/sys:ro
      # - /var/run/docker.sock:/var/run/docker.sock:rw

    environment:
      - POSTGRES_HOST=db

    env_file:
      - .env

    cap_add:
      - CAP_SYS_ADMIN

    privileged: true
    command: [ "sleep", "infinity" ]

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: [ "5432:5432" ]
    env_file:
      - .env
  # reverse-proxy:
  #   # The official v3 Traefik docker image
  #   image: traefik:v3.4
  #   # Enables the web UI and tells Traefik to listen to docker
  #   command: --api.insecure=true --providers.docker
  #   volumes:
  #     # So that Traefik can listen to the Docker events
  #     - /var/run/docker.sock:/var/run/docker.sock

  #   network_mode: host


volumes:
  pgdata:
  etc_volume:
