api:
  insecure: true

entryPoints:
  http:
    address: ":80" # Создать HTTP entrypoint на порт 80

  mysql:
    address: ":3306"

providers:
  swarm:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

  file:
    directory: "/etc/traefik/dynamic/conf"
    watch: true

experimental:
  plugins:
    sablier:
      moduleName: "github.com/acouvreur/sablier"
      version: "v1.8.0"
