"""empty message

Revision ID: 17187237806f
Revises: ff4984cee75c
Create Date: 2025-05-17 17:48:24.479422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17187237806f'
down_revision: Union[str, None] = 'ff4984cee75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mysql_databases',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('root_password',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('shared_resources')
    op.drop_table('shared_resource_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_resources',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('resource_type_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['resource_type_id'], [
                        'shared_resource_types.id'], name='shared_resources_resource_type_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='shared_resources_pkey')
                    )
    op.create_table('shared_resource_types',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='shared_resource_types_pkey')
                    )
    op.drop_table('mysql_databases')
    # ### end Alembic commands ###
