"""empty message

Revision ID: 1a7519f20188
Revises: cc4c2b9aa5ed
Create Date: 2025-05-18 18:37:06.689365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1a7519f20188'
down_revision: Union[str, None] = 'cc4c2b9aa5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_projects', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('current_timestamp'), nullable=False))
    op.add_column('student_projects', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_projects', 'updated_at')
    op.drop_column('student_projects', 'created_at')
    # ### end Alembic commands ###
