"""empty message

Revision ID: 458576d8546d
Revises: 17187237806f
Create Date: 2025-05-18 09:09:48.814754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '458576d8546d'
down_revision: Union[str, None] = '17187237806f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_templates',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('dockerfile', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('student_projects_resource_template_id_fkey',
                       'student_projects', type_='foreignkey')
    op.drop_column('student_projects', 'resource_template_id')
    op.drop_table('resource_templates')
    op.add_column('student_projects', sa.Column(
        'project_template_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'student_projects', 'project_templates', [
                          'project_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_projects', sa.Column(
        'resource_template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_projects', type_='foreignkey')
    op.create_foreign_key('student_projects_resource_template_id_fkey',
                          'student_projects', 'resource_templates', ['resource_template_id'], ['id'])
    op.drop_column('student_projects', 'project_template_id')
    op.create_table('resource_templates',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('dockerfile', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='resource_templates_pkey')
                    )
    op.drop_table('project_templates')
    # ### end Alembic commands ###
