"""empty message

Revision ID: 4b14d48a9cfe
Revises: f3b23d776759
Create Date: 2025-05-21 18:32:41.845738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b14d48a9cfe'
down_revision: Union[str, None] = 'f3b23d776759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(
                        'current_timestamp'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('project_template_id',
                              sa.Uuid(), nullable=False),
                    sa.Column('account_id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column(
                        'cpu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ram', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('byte_size', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
                    sa.ForeignKeyConstraint(['project_template_id'], [
                        'project_templates.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_column('mysql_accounts', 'student_project_id')
    # op.drop_constraint('mysql_accounts_student_project_id_fkey',
    #                    'mysql_accounts', type_='foreignkey')
    op.drop_column('groups', 'middleware_name')
    op.drop_table('student_projects')
    op.add_column('mysql_accounts', sa.Column(
        'account_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'mysql_accounts',
                          'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mysql_accounts', sa.Column('student_project_id',
                  sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mysql_accounts', type_='foreignkey')
    op.create_foreign_key('mysql_accounts_student_project_id_fkey',
                          'mysql_accounts', 'student_projects', ['student_project_id'], ['id'])
    op.drop_column('mysql_accounts', 'account_id')
    op.add_column('groups', sa.Column('middleware_name', sa.VARCHAR(
        length=265), autoincrement=False, nullable=False))
    op.create_table('student_projects',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('student_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('cpu', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('ram', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('project_template_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('byte_size', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=True),
                    sa.Column('project_url', sa.VARCHAR(), server_default=sa.text(
                        "'thesis.com'::character varying"), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['project_template_id'], [
                        'project_templates.id'], name='student_projects_project_template_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['student_id'], ['students.id'], name='student_projects_student_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='student_projects_pkey')
                    )
    op.drop_table('projects')
    # ### end Alembic commands ###
