"""empty message

Revision ID: 6112ed30c9d7
Revises: f4bee921f87f
Create Date: 2025-05-19 18:00:44.700419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6112ed30c9d7'
down_revision: Union[str, None] = 'f4bee921f87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mysql_accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('login', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('student_project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_project_id'], ['student_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mysql_databases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mysql_databases',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('root_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mysql_databases_pkey')
    )
    op.drop_table('mysql_accounts')
    # ### end Alembic commands ###
