"""empty message

Revision ID: 81e79de0d203
Revises: 6733bf2a4168
Create Date: 2025-05-22 14:47:11.536853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81e79de0d203'
down_revision: Union[str, None] = '6733bf2a4168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_images',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('dockerfile', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('projects_project_template_id_fkey',
                       'projects', type_='foreignkey')
    op.drop_column('projects', 'project_template_id')
    op.drop_table('project_templates')
    op.add_column('projects', sa.Column(
        'project_image_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'projects', 'project_images', [
                          'project_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_template_id',
                  sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_project_template_id_fkey', 'projects',
                          'project_templates', ['project_template_id'], ['id'])
    op.drop_column('projects', 'project_image_id')
    op.create_table('project_templates',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('dockerfile', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='project_templates_pkey')
                    )
    op.drop_table('project_images')
    # ### end Alembic commands ###
