"""empty message

Revision ID: ca3906bd1953
Revises: ecea92fc2a3b
Create Date: 2025-06-07 16:24:28.781938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca3906bd1953'
down_revision: Union[str, None] = 'ecea92fc2a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_project_image_id_fkey',
                       'projects', type_='foreignkey')
    op.drop_column('projects', 'project_image_id')
    op.drop_table('project_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_image_id',
                  sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('projects_project_image_id_fkey',
                          'projects', 'project_images', ['project_image_id'], ['id'])
    op.create_table('project_images',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128),
                              autoincrement=False, nullable=False),
                    sa.Column('dockerfile', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='project_images_pkey')
                    )
    # ### end Alembic commands ###
