"""empty message

Revision ID: cc4c2b9aa5ed
Revises: a8460c223838
Create Date: 2025-05-18 15:49:08.351109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc4c2b9aa5ed'
down_revision: Union[str, None] = 'a8460c223838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'middleware_name',
               existing_type=sa.VARCHAR(length=265),
               nullable=False)
    op.add_column('student_projects', sa.Column('byte_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_projects', 'byte_size')
    op.alter_column('groups', 'middleware_name',
               existing_type=sa.VARCHAR(length=265),
               nullable=True)
    # ### end Alembic commands ###
