"""empty message

Revision ID: f4bee921f87f
Revises: fbd239e9e091
Create Date: 2025-05-18 20:46:55.398195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4bee921f87f'
down_revision: Union[str, None] = 'fbd239e9e091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student_projects', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_projects', type_='foreignkey')
    # ### end Alembic commands ###
