"""empty message

Revision ID: fbd239e9e091
Revises: 1a7519f20188
Create Date: 2025-05-18 18:50:56.099459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbd239e9e091'
down_revision: Union[str, None] = '1a7519f20188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_projects', sa.Column(
        'project_url', sqlmodel.sql.sqltypes.AutoString(), server_default='thesis.com', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_projects', 'project_url')
    # ### end Alembic commands ###
