"""empty message

Revision ID: ff4984cee75c
Revises:
Create Date: 2025-05-17 17:23:35.840747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff4984cee75c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp'), nullable=True),
    sa.Column('is_stuff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=265), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_templates',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dockerfile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_resource_types',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_resources',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('resource_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['shared_resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('resource_template_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cpu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ram', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['resource_template_id'], ['resource_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('logical_limit', sa.Integer(), nullable=False),
    sa.Column('logical_used', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('students')
    op.drop_table('student_projects')
    op.drop_table('shared_resources')
    op.drop_table('shared_resource_types')
    op.drop_table('resource_templates')
    op.drop_table('groups')
    op.drop_table('accounts')
    # ### end Alembic commands ###
