quota:
  students_shared_base_dir: /students
  students_home_base_dir: /home
database:
  db: api
  user: vFaWi722cKdlA8PeXuyAYoEYzEI
  password: iXaoOngwIegUlYVkpU9wc1It1FU
  host: localhost
  port: 5432

swarm:
  overlay_network_name: thesis_default

domain: thesis.com
mysql_root_password: vFaWi722cKdlA8PeXuyAYoEYzEI
students_home_base_dir: /home
students_shared_base_dir: /students
jwt_secret: secret
